Fix time field length when us=0
jonhoo/msql-srv pull request #17
Opened 2021-05-20 12:54 UTC by simonhdickson

I noticed this when testing using sqlx client and getting off by one errors, time length should be [0, 8, 12]

https://dev.mysql.com/doc/internals/en/binary-protocol-value.html

2021-05-22 23:39 UTC, jonhoo commented
Oh, that's a good catch, thanks! I wonder how on earth it ended up as 9. While you're at it, could you also fix the fact that (as far as I can tell), we don't implement the optimization that length should be 0 if the `Duration` covers no time?

2021-05-26 08:20 UTC, simonhdickson commented
I made some changes to try and support that but I'm not sure if I'm missing some places.

2021-05-27 01:58 UTC, jonhoo requested changes
Only one small change, otherwise this looks great now, thanks!

2021-05-27 01:58 UTC, jonhoo commented on src/value/decode.rs
> +                Duration::from_secs(0)
Let's make this `return Duration::from_secs(0);` so that we can avoid placing the rest of the function body in an `else` block.

2021-05-27 07:36 UTC, simonhdickson commented
Done :slightly_smiling_face:

2021-05-29 02:50 UTC, jonhoo approved these changes
Thanks!

2021-05-29 02:51 UTC, merged