Enable returning errors after creating row writer
jonhoo/msql-srv pull request #20
Opened 2021-07-13 09:39 UTC by simonhdickson

So the issue I have is that once you create a `RowWriter` you aren't able to return an error anymore because when you call `finish_one` to get `QueryResultWriter` the client just assumes we reached the end of the result set and doesn't see the error message.

I don't think this is a total solution but works for my use case, I think the correct solution would be to either adding a `finish_error` function to `RowWriter` or to not set `last_end` if you call `finish_one`? But I'm not sure if that is a problem for other use cases.

2021-07-20 16:04 UTC, jonhoo requested changes
This is a great addition, thanks for submitting it! I wonder if `finish_error` has to also call `finish_inner` though (but not `finish_completed`)? Could you add a test case for this to make sure we encode it correctly?

2021-08-11 15:04 UTC, simonhdickson commented
I have added a test for this change, `finish_error` calls `finish_one` which is already calling `finish_inner`.

2021-08-12 01:47 UTC, jonhoo commented
Thanks! It looks like CI testing fails now?

2021-08-12 08:21 UTC, simonhdickson commented
Yes, I think that is fixed by #24 ?

2021-08-16 00:26 UTC, jonhoo commented
Merged! Could you merge from master so we can kick CI again?

2021-08-23 11:25 UTC, simonhdickson commented
Had an issue with some of the other tests, but making the change a bit less invasive seems to have fixed that.

2021-08-28 00:11 UTC, merged